shell = "zsh"

[plugins]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.spaceship]
github = "spaceship-prompt/spaceship-prompt"

[plugins.spaceship-section]
github = "spaceship-prompt/spaceship-vi-mode"
